package streams;

import java.util.stream.Collectors;
import java.util.stream.Stream;

public class StreamGenerate {
    public static void main(String[] args) {

        System.out.print("\n\nStream generated from pre-defined values: ");

        // Used in the tutorial
        var naturals = Stream.of(1, 2, 3, 4, 5).collect(Collectors.mapping(i -> i.toString(), Collectors.joining(", ")));

        // OR (This one i figured out myself)
        // var naturals = Stream.of(1, 2, 3, 4, 5).map(i -> i.toString()).collect(Collectors.joining(", "));

        System.out.println(naturals);

        System.out.print("\nStream generated by a Supplier lamba expression: ");
        var randoms = Stream.generate(() -> Math.ceil(Math.random() * 1000) / 1000) .limit(5).collect(Collectors.mapping(i -> i.toString(), Collectors.joining(", ")));
        System.out.println(randoms);

        System.out.print("\nStream generated by iteration to the intial provided value: ");
        var doubles = Stream.iterate(1, (i) -> i * 2).limit(5).collect(Collectors.mapping(i -> i.toString(), Collectors.joining(", ")));
        System.out.println(doubles + "\n\n\n");

    }
}
